name: Build and test artifacts
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: ./scripts/ci/run-frontend-tests.sh
  run-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-backend-tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-e2e-tests:
    runs-on:
      labels: Yleiskayttoiset-x86-Linux-4core
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./scripts/ci/run-e2e-tests.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
